### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ArmanNisch** [table-library/react-table-library#12]
Wondering why Typescript was not used and if there is a plan to migrate or provide type definitions? If there is a willingness I could see if I can assist with this effort.

**Comment by rwieruch** [comment]
Hi @ArmanNisch It's on the roadmap, and I would love to have in-house TS support (Rollup is already configured to support TS). However, the project I created this library for didn't use TS, so I didn't invest the initial time for it. Anyway, any help on this is greatly appreciated!

**Comment by rwieruch** [comment]
See Rollup configuration for the commented TS support: https://github.com/table-library/react-table-library/blob/master/rollup.config.js

**Comment by rwieruch** [comment]
If we would include TS, then I'd get rid of the PropTypes.

**Comment by ArmanNisch** [comment]
Hey Robin, I am slowly getting into your code (we're looking to use it for a project) and would be happy to help you with some maintenance efforts.

Before I can get started, I have 3 questions to best align with your overall coding guidelines

Do you have any preference regarding how you want to organize the types?

For example, in the case of the code found within: `/src/sort`, would you want to include the type definitions directly as part of HeaderCellSort and SortButton components or do you want a separate HeaderCellSort.types.ts / SortButton.types.ts types files or even a single separate Sort.types.ts file that would contain all types within the sort directory?

I would prefer to use Interfaces (as much as possible) — you have any preferences there?

Lastly, I like to personally always prefix my types with an "I", example ISortButton ⇒ to quickly communicate this is a type definition, is that good for you?

**Comment by rwieruch** [comment]
That sounds great @ArmanNisch !

Regarding your questions:

1) I think src/sort/types.ts would be sufficient.
2) Up to you :) 
3) Same here. Up to you :)

**Comment by rwieruch** [comment]
Done.
