### ISSUE TITLE
Need of Asana example with Virtualized scroll and fixed header

### ISSUE THREAD

**Issue by kumargauravin** [table-library/react-table-library#141]
Hi Team,

We are in need of sample data and config done for asana example on react-tables.com.
1. IN this example the column which attributes to Collapse is not part of Headers.
2. Based on 1, the sort works across Collapse but does not change order of Collapse. - Which we need

But we are not able to do so, so far.

Also, We need virutalized scroll for this view.

**Comment by rwieruch** [comment]
@kumargauravin I am available as contractor if you need someone to implement a custom table, like the Asana table, for you. If you underlying table library does not provide certain features, we can negotiate about their implementations. Hit me up @ hello@rwieruch.com
