### ISSUE TITLE
I get styled-components warning, if using react-table-library

### ISSUE THREAD

**Issue by wuarmin** [table-library/react-table-library#15]
Hey,

I have an app (create-react-app) with the `styled-components`-dependency. Now I added `react-table-library` and get following warning:

```txt
It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles to not render properly, errors during the rehydration process, a missing theme prop, and makes your application bigger without good reason.

See https://s-c.sh/2BAXzed for more info.
```
I see, we have `babel-plugin-styled-components` at package.json of `react-table-library`, but I can't figure out why the warning happened, so far.

Do you have an idea? Should we mark `styled-components` as external in this lib? Do you know a workaround for now (maybe `resolutions`)?

Thx

**Comment by rwieruch** [comment]
Thanks for coming up with this. This is indeed a problem in our current production application too.

So I use `babel-plugin-styled-components` for the `css` property in JSX which enables me to accept arbitrary style (e.g. Themes) from the outside. However, it seems to use styled components under the hood, hence the collision.

I see two paths to fix this:

1) Get rid of babel-plugin-styled-components and use something else. However, I searched for a while and couldn't find any replacement.
2) As you said, mark somehow styled-components as an dependency for this project and exclude styled-components from the build.

**Comment by wuarmin** [comment]
Hey,

I think, it's totally ok, if react-table-library uses `styled-components` under the hood (it is even an advantage). So, in my opinion the 2. path is the way to go.

1. add `style_components` to `peerDependencies`
```json
  "peerDependencies": {
    "react": "^16.13.1 || ^17",
    "react-dom": "^16.13.1 || ^17",
    "styled-components": "^5.2.3"
  },
```
2. we could add styled-components to  devDependecies
3. exclude it from the build
You already use `rollup-plugin-peer-deps-external`, which exclude the `peerDependencies`, so nothing to do here.

I forked your project and build the current code (master) locally with `yarn library:build`. After that I added it via 
```javascript
 yarn add file:../code/react-table-library/lib
```
The weird thing was, that with this I never get the warning, so I cannot test, if my changes from above would fix the warning if the library is installed from npm. I can only assume. Do you know the reason? Should I add my PR?

Thank you

**Comment by rwieruch** [comment]
Hi @wuarmin Add your PR and I will check :) 

In the long run, I'd want to find a way to have it work without SC, just to keep the dependencies to a minimum.

**Comment by wuarmin** [comment]
Hi @rwieruch,
The use of the babel-plugin, which is necessary for the `css` prop, is causing the issue, because all components with the `css` prop are transformed in *regular* SC-components by the babel-plugin.

Do you think that at some point it will be possible to have the feature without dependency

**Comment by rwieruch** [comment]
So removing the babel plugin and therefore removing SC would lead to a smaller bundle size which I would aim for. However, I couldn't find any other way to achieve what I did there. Essentially the css plugin enables the Theme feature, because developers can pass in arbitrary CSS template literals.

**Comment by wuarmin** [comment]
The babel plugin could be removed by using default SC styling. I can't think of a bettet alternative (in best case no dep) to SC either. With emotion it would be the same,

**Comment by rwieruch** [comment]
Let's keep the babel plugin for now. I have only SC before and switched to the babel plugin under the assumption that SC would go away this way. But like you said, the plugin uses SC under the hood.
