### ISSUE TITLE
bug table-library / react-table-library@1.1.0

### ISSUE THREAD

**Issue by damirsaifut** [table-library/react-table-library#18]
I think this is a bug.
"styled-components": "^5.3.0"

<img width="595" alt="image" src="https://user-images.githubusercontent.com/50329642/125749994-534048fb-3047-4430-aac1-7af4e4947af7.png">

**Comment by rwieruch** [comment]
Are you using it with NextJs/SSR? It's not working yet unfortunately https://github.com/table-library/react-table-library/issues/9
