### ISSUE TITLE
App crashes with error: React is not defined

### ISSUE THREAD

**Issue by deepakjacob** [table-library/react-table-library#39]
Steps:
1. Bootstrap an application using create-react-app (npx create-react-app my-app --template typescript)
2. Add the dependencies npm install @table-library/react-table-library @emotion/react)
3. App crashes with following error:

```
Uncaught ReferenceError: React is not defined
    at x (objectWithoutProperties.js:19:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at mountIndeterminateComponent (react-dom.development.js:20838:1)
    at beginWork (react-dom.development.js:22342:1)
    at beginWork$1 (react-dom.development.js:27219:1)
    at performUnitOfWork (react-dom.development.js:26392:1)
    at workLoopSync (react-dom.development.js:26303:1)
    at renderRootSync (react-dom.development.js:26271:1)
    at performSyncWorkOnRoot (react-dom.development.js:25924:1)
    at flushSyncCallbacks (react-dom.development.js:11982:1)


```

**Comment by allenchuang** [comment]
same here...

**Comment by rwieruch** [comment]
That's weird. I have followed your instructions and cannot see the bug happening:

1. `npx create-react-app my-app --template typescript`
2. `cd my-app`
3. `npm install @table-library/react-table-library @emotion/react`
4. `npm start`

Then I used the following implementation in the App.tsx file:

```
import {
  Table,
  Header,
  HeaderRow,
  HeaderCell,
  Body,
  Row,
  Cell,
} from '@table-library/react-table-library/table';

const list = [
  {
    id: '1',
    name: 'VSCode',
    deadline: new Date(2020, 1, 17),
    type: 'SETUP',
    isComplete: true,
  },
  {
    id: '2',
    name: 'JavaScript',
    deadline: new Date(2020, 2, 28),
    type: 'LEARN',
    isComplete: true,
  },
  {
    id: '3',
    name: 'React',
    deadline: new Date(2020, 3, 8),
    type: 'LEARN',
    isComplete: false,
  },
];

const App = () => {
  const data = { nodes: list };

  return (
    <Table data={data}>
      {(tableList) => (
        <>
          <Header>
            <HeaderRow>
              <HeaderCell>Task</HeaderCell>
              <HeaderCell>Deadline</HeaderCell>
              <HeaderCell>Type</HeaderCell>
              <HeaderCell>Complete</HeaderCell>
            </HeaderRow>
          </Header>

          <Body>
            {tableList.map((item) => (
              <Row key={item.id} item={item}>
                <Cell>{item.name}</Cell>
                <Cell>
                  {item.deadline.toLocaleDateString('en-US', {
                    year: 'numeric',
                    month: '2-digit',
                    day: '2-digit',
                  })}
                </Cell>
                <Cell>{item.type}</Cell>
                <Cell>{item.isComplete.toString()}</Cell>
              </Row>
            ))}
          </Body>
        </>
      )}
    </Table>
  );
};

export default App;
```

My package.json looks like this:

```
{
  "name": "my-app-ts",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.9.0",
    "@table-library/react-table-library": "^2.0.20",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.4.1",
    "@types/node": "^16.11.26",
    "@types/react": "^17.0.44",
    "@types/react-dom": "^17.0.15",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "5.0.0",
    "typescript": "^4.6.3",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

What's different in your setup?

**Comment by deepakjacob** [comment]
You can simulate the error mentioned  if you include the following in the App.tsx 
```

import { CompactTable } from '@table-library/react-table-library/compact';

const nodes = [
  {
    id: '0',
    name: 'Shopping List',
    deadline: new Date(2020, 1, 15),
    type: 'TASK',
    isComplete: true,
    nodes: 3,
  },
]

const COLUMNS = [
  { label: 'Task', renderCell: (item) => item.name },
  {
    label: 'Deadline',
    renderCell: (item) =>
      item.deadline.toLocaleDateString('en-US', {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
      }),
  },
  { label: 'Type', renderCell: (item) => item.type },
  {
    label: 'Complete',
    renderCell: (item) => item.isComplete.toString(),
  },
  { label: 'Tasks', renderCell: (item) => item.nodes },
];

const Component = () => {
  const data = { nodes };

  return <CompactTable columns={COLUMNS} data={data} />;
};
```

**Comment by rwieruch** [comment]
Thanks for reporting this one! Can you try again with the following version?

@table-library/react-table-library@2.0.29

**Comment by proddy** [comment]
I can't get the demos to work either, using 2.0.29 `Types of property 'nodes' are incompatible.`

**Comment by rwieruch** [comment]
The only restriction there is for nodes is that there must be an `id` of type string and if there is a property with the name `nodes` it should be an array:

https://react-table-library.com/?path=/docs/types-data--page

How does your data look like that you are passing to the table @proddy ?

**Comment by proddy** [comment]
I was using the exact example from the README.md (https://github.com/table-library/react-table-library#usage).

to get it working I had to change `const data = { nodes }` to `const data = { nodes : nodes }` and the `renderCell: (item)` to `renderCell: (item: any)` because of the noImplicitAny warning.

**Comment by deepakjacob** [comment]
@rwieruch I installed the latest one and it is working as expected. Thanks for the quick turnaround. 

Note: I tried to check the repo for the commits related to this fix. But couldn´t find the same.

**Comment by proddy** [comment]
> I was using the exact example from the README.md (https://github.com/table-library/react-table-library#usage).
> 
> to get it working I had to change `const data = { nodes }` to `const data = { nodes : nodes }` and the `renderCell: (item)` to `renderCell: (item: any)` because of the noImplicitAny warning.

@rwieruch are you going to fix the example code, or just closing/ignoring it?

**Comment by deepakjacob** [comment]
@proddy the original issue this ticket was created for, is solved so this can be closed.

Please  create another ticket to track the issue you are interested in and as always pull requests are appreciated from users ;)

**Comment by proddy** [comment]
fair comment. I'm still evaluating this library and finding many inconsistencies. If I decide to use it I'll surely submit back PRs. My point is that others may experience the same issues and give up, which would be a shame as there is a lot of potential with this library

**Comment by rwieruch** [comment]
Please open an issue for every inconsistency you find. For your reported issue about the types, the example in the README.md does not use TS. I'd expect if someone is using TS to fill in the type declarations that are not part of the library.
