### ISSUE TITLE
question: how to toggle sort between 3 states (none, sort, sort reverse)

### ISSUE THREAD

**Issue by proddy** [table-library/react-table-library#49]
Is there a way to use the `onToggleSort` function to cylce through 3 states (NONE + sorting by sortKey) instead of only between sorting & reverse sorting?

if that makes sense.

**Comment by rwieruch** [comment]
Can you try the latest version [3.1.0](https://github.com/table-library/react-table-library/releases/tag/v3.1.0) with this [new option](https://github.com/table-library/react-table-library/compare/v3.0.1...v3.1.0#diff-d31ffa0161e8f2c5ff8b8f8e102ba6d8ea5ab7b9d89eafe5c5608dbfc435bfa0R174) passed to `useSort`?

**Comment by proddy** [comment]
Cool. That was quick. Will test tonight

**Comment by proddy** [comment]
wonderful, works like a charm. thanks!
