### ISSUE TITLE
Question: Row click not cancelable by child event stoppropagation?

### ISSUE THREAD

**Issue by bay-jacewhitten** [table-library/react-table-library#50]
Hi there guys,

I was messing with the library and so far love it. 

This is more of a question than a bug or issue, but I was not able to construct a way for the row click to be cancelled by the cell click. I can see my child cell is cancelling, but the row click never receives the stoppropagation call from the child element. And so the row click fires along with the cell click.  I tried a few 'tricks' but had to move on for the sake of time, and just add the click event to certain cells, etc. Not super ideal, but is what it is.

My quick investigation lead down the path that the react synthetic events was not making it to the Row which is using native events. Wasn't able to quite confirm this, and still couldn't get the results I was expecting. I am using the composable table, so maybe there is something I am missing or not wiring up correctly?

Thanks in advance for any feedback or help!

**Comment by rwieruch** [comment]
It should be fixed over here https://github.com/table-library/react-table-library/commit/7ea2df4680d3e02a6d6db90d54c3c2506bf4d05f So in version 3.1.2 it should be possible to cancel a row click via a cell click by using event.stopPropagation for the cell click.

This does not work when using the double click feature unfortunately -- which has been the culprit in the first place.

**Comment by bay-jacewhitten** [comment]
Ah ok, thank you for the clarification and help.
