### ISSUE TITLE
bug(typescript): Could not find declaration file for module @table-library/react-table-library/mantine

### ISSUE THREAD

**Issue by CUexter** [table-library/react-table-library#51]
I cant seem to import it without this error
```javascript
import {
  DEFAULT_OPTIONS,
  getTheme,
} from "@table-library/react-table-library/mantine";
```
I think the type is already in `@table-library/react-table-libary/themes/mantine` but I don't know how to fix it.

**Comment by rwieruch** [comment]
Fixed in https://github.com/table-library/react-table-library/commit/8dece67d428285e36ab3024f24c2345296ca27ed Can you try version 3.1.1 ?

**Comment by CUexter** [comment]
Wow that was quick thank you
