### ISSUE TITLE
Upgrade react-window to 1.8.7 to avoid warnings

### ISSUE THREAD

**Issue by proddy** [table-library/react-table-library#54]
With React 18 the library will give warnings.

Can you update the react-window package dependency to use version 1.8.7 as its fixes the peerDependencies. See https://github.com/bvaughn/react-window/issues/623

Also I think react-virtualized-auto-size will also give warnings but that package hasn't been updated.

**Comment by proddy** [comment]
@rwieruch ?

**Comment by rwieruch** [comment]
Done in https://github.com/table-library/react-table-library/commit/eca36827f7c5a1bfb86c9e5139315e1110d6e428 and available in v3.1.3 

Sorry for the late reply @proddy !
