### ISSUE TITLE
React filtering with multiple columns is not giving the expected output

### ISSUE THREAD

**Issue by hersheykurra** [table-library/react-table-library#57]
In this code, you used filtering using a single column (item.type). I am trying to use multiple columns and this code does not work as expected.
 
For Example see the below(made changes to the code on the website by adding one more filter with a different column):
 
**const data = {
    nodes: nodes.filter(
      (item) =>
        (filters.includes('SETUP') && item.type === 'SETUP') ||
        (filters.includes('LEARN') && item.type === 'LEARN') ||
           (filters.includes(‘2’) && item.Severity === ‘2’)
    ),
  };**
 
So here, since I am using both Severity and type both the columns, my results are not as expected. The above works perfectly well if I use a single column.
Please help me with this!

**Comment by rwieruch** [comment]
Can you create a reproducible example on https://codesandbox.io/ ?

**Comment by hersheykurra** [comment]
please go through: https://codesandbox.io/s/bold-sunset-emyb4o?file=/src/DataTable.js

I replicated the exact issue i am facing.

**Comment by rwieruch** [comment]
Does this Codesandbox start for you? For me it shows "Installing Dependencies 1/20 (web-vitals)"

**Comment by rwieruch** [comment]
Thanks. It works. Can you give me a scenario of two filters unselected (since all filters are initially selected) where you don't get the expected output?

**Comment by hersheykurra** [comment]
Thanks for the code Robin! I've tried the same today morning but, 
The issue i am facing is.. if i select JUST active & mitigated checkboxes, it should return me all the records with this status. But since we are using && between different columns, it requires me to definitely choose one of the options in other columns(Severity, CreationDate and IncidentType)

Could you suggest if there's a way I can get the data displayed with whatever options i choose without having to definitely choose one of the options in each category. (For example, if you uncheck them all and check just active, it should return me all the data with status as active)

**Comment by rwieruch** [comment]
Sorry for being late here.

The issue is not with the library, but with your booleans. I made the example smaller by removing some of your filters. In the following we have only Incident Types and Status:

![Screenshot 2022-06-22 at 13 42 15](https://user-images.githubusercontent.com/2479967/175020875-33e6328b-2dad-44b0-bf20-dca96b130948.jpg)

The selection shows no results even though you want to show everything, because all Status are selected. The issue is in this code block:

```
const data = {
    nodes: list.filter(
      (item) =>
        ((filters.includes("ACTIVE") && item.Status === "ACTIVE") ||
          (filters.includes("MITIGATED") && item.Status === "MITIGATED") ||
          (filters.includes("RESOLVED") && item.Status === "RESOLVED")) &&
        ((filters.includes("CRI") &&
          item.IncidentType === "CustomerReported") ||
          (filters.includes("OTHERS") && item.IncidentType === "LiveSite"))
    )
  };
```

Which should be: 

```
  const data = {
    nodes: list.filter(
      (item) =>
        (filters.includes("ACTIVE") && item.Status === "ACTIVE") ||
        (filters.includes("MITIGATED") && item.Status === "MITIGATED") ||
        (filters.includes("RESOLVED") && item.Status === "RESOLVED") ||
        (filters.includes("CRI") && item.IncidentType === "CustomerReported") ||
        (filters.includes("OTHERS") && item.IncidentType === "LiveSite")
    )
  };
```

Try it yourself: https://codesandbox.io/s/billowing-wildflower-2gjj35?file=/src/App.js:981-1416
