### ISSUE TITLE
feature request: allow user config the scrollbar component for compact table scroll

### ISSUE THREAD

**Issue by coolRoger** [table-library/react-table-library#60]
I am using mantine theme for the compact table, but mantineUI provides custom scrollbar component called ScrollArea, I want to use ScrollArea for table scrollbar instead of the browser native scrollbar, have any ideas or options to achieve this need?

**Comment by sep2** [comment]
Also looking for this issue. Did you find anything?

**Comment by rwieruch** [comment]
What specific features are you missing from the `ScrollArea ` component? The only thing I can think of would be the "scroll to position" feature.

**Comment by coolRoger** [comment]
> What specific features are you missing from the `ScrollArea ` component? The only thing I can think of would be the "scroll to position" feature.

also for keeping the same scroll bar style result with Windows and Mac OS
