### ISSUE TITLE
props.item in tree sub-node has unexpected value

### ISSUE THREAD

**Issue by rehevkor5** [table-library/react-table-library#70]
When expanding one of the root nodes of a table with tree enabled the item for that row is not as expected.

My table data is simple:

```
const tableData = {
    nodes: [
      {
        id: '1',
        terms: "zero",
        num_docs: 4,
        nodes: [
          {
            id: '2',
            terms: "one",
            num_docs: 12,
            nodes: null
          },
          {
            id: '3',
            terms: "two",
            num_docs: 12,
            nodes: null
          }
        ]
      }
    ]
  };
```

I'm expecting something along these lines:

```
{
    "id": "1",
    "terms": "zero",
    "num_docs": 4,
    "nodes": [
        "2",
        "3"
    ],
    "treeXLevel": 0,
    "treeYLevel": 0,
    "parentNode": {
        (truncated)
    },
    "ancestors": [
       (truncated)
    ]
}
```

but instead I'm getting:

```
{
    "nodes": [
        {
            "id": "1",
            "terms": "zero",
            "num_docs": 4,
            "nodes": [
                {
                    "id": "2",
                    "terms": "one",
                    "num_docs": 12,
                    "nodes": null
                },
                {
                    "id": "3",
                    "terms": "two",
                    "num_docs": 12,
                    "nodes": null
                }
            ]
        }
    ],
    "[object Object],[object Object]": [
        "1"
    ]
}
```

Also, I'm seeing this warning:

```
Warning: Each child in a list should have a unique "key" prop.
```

The warning appears to come from a `<D>` which has no `key` attribute, unlike the root nodes. Also, its `props.item` is shown by the React plugin as: `{[object Object],[object Object]: Array(1), nodes: …}`. Specifically, it has an attribute named `"[object Object],[object Object]"`. The value of that property is `["1"]`. Also, its `nodes` attribute looks different than what's on the others, and it doesn't have attributes such as `ancestors` or `parentNode`. So it seems like something strange is happening.

Could this be because I am using React 18.2.0? I am using 4.0.10 of react-table-library.

**Comment by rehevkor5** [comment]
My word, this was annoying to track down! Turns out that somehow my version of `react-scripts` (from create-react-app) got accidentally downgraded from 5.01 to 2.1.3 during development without me noticing. After fixing that, the table works properly! I am guessing the problem was probably caused by an old Babel transpiling certain code incorrectly.

**Comment by rwieruch** [comment]
Oh damn. Sorry that you had to go through this. I didn't had any time earlier to look at this, but I glad you figured it out. Let me know if you have any other feedback for the library!

**Comment by rwieruch** [comment]
Thanks for the sponsoring @rehevkor5 ❤️
