### ISSUE TITLE
How to implement "expand all children"?

### ISSUE THREAD

**Issue by freder** [table-library/react-table-library#72]
in a tree view I would like to make it so that a normal `click` opens the item, and `alt+click` open the item and all its descendants. – how would I go about implementing this?

**Comment by freder** [comment]
apparently there is an [ADD_BY_ID_RECURSIVELY](https://github.com/table-library/react-table-library/search?q=ADD_BY_ID_RECURSIVELY) action type, which sounds interesting; but how do I dispatch it in my code?

**Comment by rwieruch** [comment]
https://github.com/table-library/react-table-library/releases/tag/v4.0.11 implements this feature. On https://react-table-library.com/ check out the Stories:

- Features / Tree / Toggle All
- Features / Tree / Toggle Recursively

In general you will find all the available functions on the returned object from the feature hook. E.g. `const tree = useTree(...)` and then `console.log(tree.fns)`.

I hope this helps!

**Comment by freder** [comment]
@rwieruch great, thank you!

I had seen `tree.fns` but was probably thrown off by the naming: `on[...]` made me think it's an event handler of sorts. should have looked more closely!

**Comment by rwieruch** [comment]
You may be right her, thanks! What would be a good naming?

**Comment by freder** [comment]
I think simply dropping the `on` prefix might already be enough: `onRemoveByIdRecursively` → `removeByIdRecursively`
what do you think?

**Comment by tsingson** [comment]
> https://github.com/table-library/react-table-library/releases/tag/v4.0.11 implements this feature (install 4.0.11).
> 
> On https://react-table-library.com/ check out the Stories:
> 
> * Features / Tree / Toggle All
> * Features / Tree / Toggle Recursively
> 
> In general you will find all the available functions on the returned object from the feature hook. E.g. `const tree = useTree(...)` and then `console.log(tree.fns)`.
> 
> I hope this helps!

hi, 
```
    tree.fns.onToggleAll({
      isCarryForward: true,
      isPartialToAll: true,
    });
```

call twin will disable expand all, 
so, how to keep all tree expand at refresh current tree ??
