### ISSUE TITLE
unable set Width to cell for compact table library

### ISSUE THREAD

**Issue by gudivadadilip** [table-library/react-table-library#76]
unable set Width to cell for compact table library

like label ,renderCell any possible to set width props in react table library

**Comment by rwieruch** [comment]
Please check out the following Story: https://react-table-library.com/?path=/docs/features-layout--base#custom You need to use the theme for setting a custom layout. Let me know if this helps.

**Comment by gudivadadilip** [comment]
![image](https://user-images.githubusercontent.com/110836329/192504445-57532628-8dab-4464-8f99-93a4f5fd25d7.png)
is any where we can set each column with width property? for particular column i need to set 200px width or percentage

**Comment by rwieruch** [comment]
Yes, you can. I have linked the documentation in my previous comment. There you will find how to set the width of each column, either by using percentage or pixel.

**Comment by ujuanwork** [comment]
This isn't working anymore.

**Comment by cerahmed** [comment]
@ujuanwork had to include `!important` for it to work.
