### ISSUE TITLE
default open to certain level of tree table

### ISSUE THREAD

**Issue by salad5f6** [table-library/react-table-library#79]
Can we have a feature of setting certain tree table's row already open to a certain level ?

**Comment by rwieruch** [comment]
Hey @salad5f6 it's already possible. You can set up everything for the tree feature. Afterward, you have access to all the internal functions by using the tree object:

```
const tree = useTree(data, {
  state: { ids: ['1', '2'] },
  onChange: ...
});
```

If you don't have the ids from the beginning, you can also set the state afterward by using the tree object:

```
React.useEffect(() => {
  tree.fns.onAddAll(myIds);
}, []);
````
