### ISSUE TITLE
TableNode.id string or number

### ISSUE THREAD

**Issue by gius** [table-library/react-table-library#93]
Many entities have numeric ids. Does it make sense to you to update `TableNode.id` to allow numbers as well?

```
export type TableNode = {
  id: string | number;
  nodes?: TableNode[] | Nullish;
  [prop: string]: any;
};
```

**Comment by rakhaxor** [comment]
Hello there, I was wondering if there are any updates? I am modifying the ids right now from int to string while passing to table.

**Comment by rwieruch** [comment]
Can someone try version 4.1.0-beta.0 with `npm install @table-library/react-table-library@4.1.0-beta.0` ? It should have the number support for the identifier.
