### ISSUE TITLE
Allow className to Table

### ISSUE THREAD

**Issue by rakhaxor** [table-library/react-table-library#95]
That would be super helpful if we could pass classnames to the table. I am not sure if there's a way to do it right now.

**Comment by mondwan** [comment]
https://github.com/table-library/react-table-library/blob/v4.0.25/src/table/Table/index.tsx#L70

If you don't mind, you can just try setting the className in Table's props. It may fit your need

**Comment by rakhaxor** [comment]
> https://github.com/table-library/react-table-library/blob/v4.0.25/src/table/Table/index.tsx#L70
> 
> If you don't mind there is an extra css class, you can just try setting the className in Table's props. It may fit your need

Oh I didn't know I could do it like this. Thank you so much for the help!!

**Comment by rwieruch** [comment]
Thanks @mondwan for helping out here! 💯
