### ISSUE TITLE
Looks like the documentation site is broken?

### ISSUE THREAD

**Issue by lucastobrazil** [table-library/react-table-library#97]
404 error thrown on the JS bundle. just raising up - maybe needs a re-deploy :)

**Comment by lucastobrazil** [comment]
I was wrong. Closing!

**Comment by rwieruch** [comment]
@lucastobrazil <3 :)

**Comment by lucastobrazil** [comment]
@rwieruch hello old friend! Just circling back on this one, someone else in my team noticed the issue too. I think it was the "MyGlue" Chrome extension which we had installed (it is a password manager). Just FYI that seemed to be what caused the issue. No idea how/why but writing it here in case anyone else ever experiences it. Hope you're well Robin!
