### ISSUE TITLE
Update react-virtualized-auto-sizer dependency to support react 18

### ISSUE THREAD

**Issue by ivanvaccari** [table-library/react-table-library#99]
The current dependency "react-virtualized-auto-sizer" is fixed to 1.0.6 which in turn lock the version to be lower than 18.

react-virtualized-auto-sizer@1.0.7 updates dependency to include also react 18. 

By updating it i can remove npm overrides which are causing me quite a lot of headaches 😄 

Thanks

**Comment by proddy** [comment]
how did you fix that? Because I'm also tired of all the warnings in my project. We tried before with https://github.com/table-library/react-table-library/commit/d225372db6ca476bb40c285a16dabc1e18c9ad5b#commitcomment-83185847

**Comment by rwieruch** [comment]
Oh, there seems to be a new version for React 18 finally. Anyone who wants to open a PR? :)

**Comment by proddy** [comment]
I can do that. 

btw there are other libs that could be updated too:

![image](https://user-images.githubusercontent.com/1230712/218255641-e88fdccc-5f18-4d47-a1de-f1a7a201053e.png)
